services:
  - type: web
    name: pdf-ai-django
    env: python
    plan: free
    buildCommand: "cd web && python manage.py collectstatic --noinput"
    startCommand: "cd web && gunicorn mysite.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mysite.settings
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "pdf-ai-django.onrender.com"
